// Generated by scripts/generate-project-image-dimensions.mjs from the local project photos.
// Width and height include EXIF orientation so reserved space matches browser display.

export const projectImageDimensions: Record<string, { width: number; height: number }> = {
  "/images/projects/_review/bathroom-after/img_7547.jpg": {
    width: 1496,
    height: 1496,
  },
  "/images/projects/_review/duplicates/basement-epoxy-floor-big-screen-2.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/_review/duplicates/bathroom-after-2.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/_review/duplicates/bathroom-after-4-2.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/_review/duplicates/bathroom-before-1-2.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/_review/duplicates/bathroom-before-1.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/_review/duplicates/bathroom-before-2-2.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/_review/duplicates/bathroom-before-2.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/_review/duplicates/bathroom-before-3-2.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/_review/duplicates/bathroom-before-4-2.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/_review/duplicates/bathroom-finished-2-2.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/_review/duplicates/bathroom-finished1-2.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/_review/duplicates/bathroom-finished1.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/_review/duplicates/bathroom-shelves-corner-2.jpg": {
    width: 4284,
    height: 5712,
  },
  "/images/projects/_review/duplicates/before-after-patio_mp4_hd.original.jpg": {
    width: 858,
    height: 720,
  },
  "/images/projects/_review/duplicates/big-screen-basement-2.jpg": {
    width: 4032,
    height: 3024,
  },
  "/images/projects/_review/duplicates/finished-room-2.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/_review/duplicates/frontier-final-2.jpg": {
    width: 4032,
    height: 3024,
  },
  "/images/projects/_review/duplicates/kitchen-1-2.jpg": {
    width: 4032,
    height: 3024,
  },
  "/images/projects/_review/duplicates/pace-1-2.jpg": {
    width: 4032,
    height: 3024,
  },
  "/images/projects/_review/duplicates/pace-1.jpg": {
    width: 4032,
    height: 3024,
  },
  "/images/projects/_review/duplicates/pace-2-2.jpg": {
    width: 4032,
    height: 3024,
  },
  "/images/projects/_review/duplicates/pace-2.jpg": {
    width: 4032,
    height: 3024,
  },
  "/images/projects/_review/duplicates/pace-5.jpg": {
    width: 4032,
    height: 3024,
  },
  "/images/projects/_review/duplicates/pace.jpg": {
    width: 4032,
    height: 3024,
  },
  "/images/projects/_review/duplicates/parkway-epoxy.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/_review/exterior-stone-siding/img_8216.jpg": {
    width: 2000,
    height: 1500,
  },
  "/images/projects/_review/exterior-stone-siding/img_8219.jpg": {
    width: 2000,
    height: 1500,
  },
  "/images/projects/_review/exterior-stone-siding/img_8220.jpg": {
    width: 2000,
    height: 1500,
  },
  "/images/projects/allentown-commercial-bathroom/after/floor-after.png": {
    width: 470,
    height: 788,
  },
  "/images/projects/allentown-commercial-bathroom/after/hallway-after.png": {
    width: 470,
    height: 788,
  },
  "/images/projects/allentown-commercial-bathroom/after/sink-area-after-preview.webp": {
    width: 470,
    height: 788,
  },
  "/images/projects/allentown-commercial-bathroom/after/sink-area-after.png": {
    width: 470,
    height: 788,
  },
  "/images/projects/allentown-commercial-bathroom/after/stall-finished.jpg": {
    width: 768,
    height: 1024,
  },
  "/images/projects/allentown-commercial-bathroom/before/floor-before.png": {
    width: 470,
    height: 788,
  },
  "/images/projects/allentown-commercial-bathroom/before/hallway-before.png": {
    width: 470,
    height: 788,
  },
  "/images/projects/allentown-commercial-bathroom/before/sink-area-before.png": {
    width: 470,
    height: 788,
  },
  "/images/projects/allentown-commercial-bathroom/marketing/floor-before-after.png": {
    width: 940,
    height: 788,
  },
  "/images/projects/allentown-commercial-bathroom/marketing/hallway-before-after.png": {
    width: 940,
    height: 788,
  },
  "/images/projects/allentown-commercial-bathroom/marketing/sink-area-before-after.png": {
    width: 940,
    height: 788,
  },
  "/images/projects/allentown-exterior-log-home/after/front-finished-preview.webp": {
    width: 1600,
    height: 2133,
  },
  "/images/projects/allentown-exterior-log-home/after/front-finished.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/allentown-exterior-log-home/after/garage-elevation.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/allentown-exterior-log-home/process/lift-access-work.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/allentown-flooring-replacement/after/fireplace-wall-renovation.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/allentown-flooring-replacement/after/living-room-finished-preview.webp": {
    width: 1600,
    height: 2133,
  },
  "/images/projects/allentown-flooring-replacement/after/living-room-finished.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/allentown-kitchen-upgrade/after/kitchen-high-end-island.jpg": {
    width: 1440,
    height: 1080,
  },
  "/images/projects/allentown-kitchen-upgrade/after/kitchen-remodel-finishes.jpg": {
    width: 4032,
    height: 3024,
  },
  "/images/projects/allentown-kitchen-upgrade/after/kitchen-white-cabinets.jpg": {
    width: 1500,
    height: 2000,
  },
  "/images/projects/allentown-kitchen-upgrade/hero/kitchen-high-end-hero-preview.webp": {
    width: 1440,
    height: 1080,
  },
  "/images/projects/allentown-kitchen-upgrade/hero/kitchen-high-end-hero.jpg": {
    width: 1440,
    height: 1080,
  },
  "/images/projects/beige-bathroom-before-after/beige-bathroom-layout-board-1-preview.webp": {
    width: 1080,
    height: 1080,
  },
  "/images/projects/beige-bathroom-before-after/beige-bathroom-layout-board-1.png": {
    width: 1080,
    height: 1080,
  },
  "/images/projects/beige-bathroom-before-after/beige-bathroom-layout-board-2.png": {
    width: 1080,
    height: 1080,
  },
  "/images/projects/berks-county-ranch-exterior/after/exterior-refresh-preview.webp": {
    width: 1600,
    height: 1200,
  },
  "/images/projects/berks-county-ranch-exterior/after/exterior-refresh.jpg": {
    width: 2048,
    height: 1536,
  },
  "/images/projects/bethlehem-bathroom-refresh/after/bathroom-after-shower-preview.webp": {
    width: 1600,
    height: 2133,
  },
  "/images/projects/bethlehem-bathroom-refresh/after/bathroom-after-shower.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/bethlehem-bathroom-refresh/after/bathroom-after-vanity-preview.webp": {
    width: 1600,
    height: 2133,
  },
  "/images/projects/bethlehem-bathroom-refresh/after/bathroom-after-vanity.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/bethlehem-bathroom-refresh/after/bathroom-after-vanity.png": {
    width: 768,
    height: 1024,
  },
  "/images/projects/bethlehem-bathroom-refresh/after/bathroom-door-open-preview.webp": {
    width: 1600,
    height: 2133,
  },
  "/images/projects/bethlehem-bathroom-refresh/after/bathroom-door-open.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/bethlehem-bathroom-refresh/after/bathroom-finished-shower-detail-preview.webp": {
    width: 1600,
    height: 2133,
  },
  "/images/projects/bethlehem-bathroom-refresh/after/bathroom-finished-shower-detail.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/bethlehem-bathroom-refresh/after/bathroom-shelves-corner.jpg": {
    width: 4284,
    height: 5712,
  },
  "/images/projects/bethlehem-bathroom-refresh/before/bathroom-before-shower.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/bethlehem-bathroom-refresh/before/bathroom-before-tile.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/bethlehem-drywall-finish-repair/after/finished-room-preview.webp": {
    width: 1600,
    height: 2133,
  },
  "/images/projects/bethlehem-drywall-finish-repair/after/finished-room.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/bethlehem-exterior-staircase/after/staircase-finished-preview.webp": {
    width: 560,
    height: 760,
  },
  "/images/projects/bethlehem-exterior-staircase/after/staircase-finished.jpg": {
    width: 560,
    height: 760,
  },
  "/images/projects/bethlehem-interior-flooring-refresh/after/flooring-refresh-preview.webp": {
    width: 576,
    height: 432,
  },
  "/images/projects/bethlehem-interior-flooring-refresh/after/flooring-refresh.jpg": {
    width: 576,
    height: 432,
  },
  "/images/projects/bethlehem-pool-patio/after/pool-patio-overview-preview.webp": {
    width: 1600,
    height: 1200,
  },
  "/images/projects/bethlehem-pool-patio/after/pool-patio-overview.jpg": {
    width: 4032,
    height: 3024,
  },
  "/images/projects/bethlehem-pool-patio/after/pool-patio-steps.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/bethlehem-pool-patio/before/pool-patio-before-preview.webp": {
    width: 1600,
    height: 2133,
  },
  "/images/projects/bethlehem-pool-patio/before/pool-patio-before.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/blue-kitchen-cabinet-counters/after/01-blue-kitchen-2.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/blue-kitchen-cabinet-counters/after/02-blue-kitchen-after_.jpg": {
    width: 4032,
    height: 3024,
  },
  "/images/projects/blue-kitchen-cabinet-counters/after/03-blue-kitchen-cabinets-1.jpg": {
    width: 838,
    height: 2046,
  },
  "/images/projects/blue-kitchen-cabinet-counters/after/04-blue-kitchen-cabinets-done.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/blue-kitchen-cabinet-counters/after/05-blue-kitchen-cabinets-finished-2-preview.webp": {
    width: 1600,
    height: 2133,
  },
  "/images/projects/blue-kitchen-cabinet-counters/after/05-blue-kitchen-cabinets-finished-2.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/blue-kitchen-cabinet-counters/marketing/01-blue-kitchen-cabinet-layout-diagram.png": {
    width: 2778,
    height: 1284,
  },
  "/images/projects/blue-kitchen-cabinet-counters/process/01-blue-kitchen-cabinets-counter-top-install.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/blue-kitchen-cabinet-counters/process/02-blue-kitchen-cabinets-process.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/01-img_7761-preview.webp": {
    width: 1600,
    height: 2133,
  },
  "/images/projects/fire-damage-documentation/after/01-img_7761.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/02-img_7762.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/03-img_7764.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/04-img_7765.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/05-img_7766.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/06-img_7768.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/07-img_7769.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/08-img_7770.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/09-img_8454.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/10-img_8455.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/11-img_8456.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/12-img_8457.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/13-img_8458.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/14-img_8459-preview.webp": {
    width: 1600,
    height: 2133,
  },
  "/images/projects/fire-damage-documentation/after/14-img_8459.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/15-img_8460.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/16-img_8461.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/17-img_8462.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/18-img_8463.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/19-img_8464.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/20-img_8465.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/21-img_8466.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/22-img_8467.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/23-img_8468.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/24-img_8469.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/25-img_8470.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/26-img_8471.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/27-img_8472.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/28-img_8473.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/29-img_8474.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/30-img_8475.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/31-img_8476.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/32-img_8477.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/33-img_8478.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/34-img_8479.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/35-img_8480.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/fire-damage-documentation/after/36-img_8933.jpg": {
    width: 4032,
    height: 3024,
  },
  "/images/projects/fire-damage-documentation/after/37-img_8934.jpg": {
    width: 4032,
    height: 3024,
  },
  "/images/projects/fire-damage-documentation/after/38-img_8935.jpg": {
    width: 4032,
    height: 3024,
  },
  "/images/projects/fireplace-construction-project/after/bathroom-tile-in-progress.jpg": {
    width: 1496,
    height: 1496,
  },
  "/images/projects/fireplace-construction-project/after/fireplace-hearth-finished-preview.webp": {
    width: 1496,
    height: 1496,
  },
  "/images/projects/fireplace-construction-project/after/fireplace-hearth-finished.jpg": {
    width: 1496,
    height: 1496,
  },
  "/images/projects/fogelsville-basement-in-progress/process/basement-process-bathroom-plumbing-rough-in-supply-drain.jpg":
    {
      width: 3024,
      height: 4032,
    },
  "/images/projects/fogelsville-basement-in-progress/process/basement-process-hallway-framing-drywall-stairway-electrical-boxes.jpg":
    {
      width: 3024,
      height: 4032,
    },
  "/images/projects/fogelsville-basement-in-progress/process/basement-process-mechanical-room-framing-tankless-water-heater.jpg":
    {
      width: 3024,
      height: 4032,
    },
  "/images/projects/fogelsville-basement-in-progress/process/basement-process-metal-stud-framing-bathroom-rough-in.jpg":
    {
      width: 3024,
      height: 4032,
    },
  "/images/projects/fogelsville-basement-in-progress/process/basement-process-metal-stud-framing-ductwork-chase-detail.jpg":
    {
      width: 3024,
      height: 4032,
    },
  "/images/projects/fogelsville-basement-in-progress/process/basement-process-staircase-framing-ceiling-grid-aquarium-wall.jpg":
    {
      width: 3024,
      height: 4032,
    },
  "/images/projects/fogelsville-basement-in-progress/process/basement-process-stairway-view-framing-electrical-panel.jpg":
    {
      width: 3024,
      height: 4032,
    },
  "/images/projects/fogelsville-basement-in-progress/process/basement-process-utility-area-insulation-ductwork-materials.jpg":
    {
      width: 3024,
      height: 4032,
    },
  "/images/projects/fogelsville-basement-in-progress/process/basement-process-wide-view-ceiling-framing-insulation-hvac.jpg":
    {
      width: 3024,
      height: 4032,
    },
  "/images/projects/fogelsville-basement-in-progress/process/basement-process-wide-view-framing-insulation-bathroom-rough-in.jpg":
    {
      width: 3024,
      height: 4032,
    },
  "/images/projects/frontier-patio-gable-roof/after/angle-1-preview.webp": {
    width: 1600,
    height: 1200,
  },
  "/images/projects/frontier-patio-gable-roof/after/angle-1.jpg": {
    width: 4032,
    height: 3024,
  },
  "/images/projects/frontier-patio-gable-roof/after/angle-2.jpg": {
    width: 4032,
    height: 3024,
  },
  "/images/projects/frontier-patio-gable-roof/after/finished-alt.jpg": {
    width: 4032,
    height: 3024,
  },
  "/images/projects/frontier-patio-gable-roof/after/finished-overview-preview.webp": {
    width: 1600,
    height: 1200,
  },
  "/images/projects/frontier-patio-gable-roof/after/finished-overview.jpg": {
    width: 4032,
    height: 3024,
  },
  "/images/projects/frontier-patio-gable-roof/after/patio-finished.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/frontier-patio-gable-roof/process/construction-site.jpg": {
    width: 4032,
    height: 3024,
  },
  "/images/projects/frontier-patio-gable-roof/process/patio-construction.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/hamburg-laundry-bathroom/after/laundry-bathroom-doorway-view-preview.webp": {
    width: 1500,
    height: 2000,
  },
  "/images/projects/hamburg-laundry-bathroom/after/laundry-bathroom-doorway-view.jpg": {
    width: 1500,
    height: 2000,
  },
  "/images/projects/hamburg-laundry-bathroom/after/laundry-bathroom-full-view.jpg": {
    width: 1500,
    height: 2000,
  },
  "/images/projects/hamburg-laundry-bathroom/after/laundry-bathroom-overview.jpg": {
    width: 1500,
    height: 2000,
  },
  "/images/projects/hamburg-laundry-bathroom/after/vanity-toilet-and-shelving.jpg": {
    width: 1500,
    height: 2000,
  },
  "/images/projects/hamburg-laundry-bathroom/after/washer-and-storage-detail.jpg": {
    width: 1500,
    height: 2000,
  },
  "/images/projects/hamburg-laundry-bathroom/after/window-trim-and-washer.jpg": {
    width: 1500,
    height: 2000,
  },
  "/images/projects/hamburg-laundry-bathroom/before/laundry-bathroom-before.jpg": {
    width: 1500,
    height: 2000,
  },
  "/images/projects/lehigh-valley-basement-theater/after/epoxy-floor-big-screen.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/lehigh-valley-basement-theater/after/media-room-big-screen-preview.webp": {
    width: 1600,
    height: 1200,
  },
  "/images/projects/lehigh-valley-basement-theater/after/media-room-big-screen.jpg": {
    width: 4032,
    height: 3024,
  },
  "/images/projects/lehigh-valley-basement-theater/after/wide-angle-room-flow.jpg": {
    width: 4032,
    height: 3024,
  },
  "/images/projects/lehigh-valley-basement-theater/after/wide-view-layout.jpg": {
    width: 4032,
    height: 3024,
  },
  "/images/projects/lehigh-valley-exterior-refresh/after/exterior-after-preview.webp": {
    width: 946,
    height: 2048,
  },
  "/images/projects/lehigh-valley-exterior-refresh/after/exterior-after.jpg": {
    width: 946,
    height: 2048,
  },
  "/images/projects/lehigh-valley-exterior-refresh/after/exterior-finished-preview.webp": {
    width: 720,
    height: 1544,
  },
  "/images/projects/lehigh-valley-exterior-refresh/after/exterior-finished.jpg": {
    width: 720,
    height: 1544,
  },
  "/images/projects/lehigh-valley-exterior-refresh/before/exterior-before.jpg": {
    width: 946,
    height: 2048,
  },
  "/images/projects/lehigh-valley-exterior-refresh/marketing/exterior-before-after.jpg": {
    width: 1892,
    height: 2048,
  },
  "/images/projects/lehigh-valley-exterior-refresh/process/exterior-in-progress.jpg": {
    width: 720,
    height: 1544,
  },
  "/images/projects/reading-commercial-bar-window/after/window-upgrade-preview.webp": {
    width: 1600,
    height: 1200,
  },
  "/images/projects/reading-commercial-bar-window/after/window-upgrade.jpg": {
    width: 4032,
    height: 3024,
  },
  "/images/projects/ryan-bathroom/after/ryans-bathroom-finished-preview.webp": {
    width: 1600,
    height: 2133,
  },
  "/images/projects/ryan-bathroom/after/ryans-bathroom-finished.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/ryan-bathroom/before/ryans-bathroom-before.jpg": {
    width: 1242,
    height: 2208,
  },
  "/images/projects/ryan-bedroom/after/01-interior-refresh-blue-completed-preview.webp": {
    width: 1600,
    height: 2133,
  },
  "/images/projects/ryan-bedroom/after/01-interior-refresh-blue-completed.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/ryan-bedroom/after/02-interior-refresh-blue-1.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/ryan-bedroom/after/03-interior-refresh-blue-3.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/ryan-bedroom/after/04-interior-refresh-blue-4.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/ryan-bedroom/after/05-interior-refresh-blue-done.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/ryan-bedroom/before/01-interior-refresh-before.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/ryan-bedroom/before/02-interior-refresh-blue-before-2.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/ryan-bedroom/process/01-interior-refresh-blue-2-process.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/ryan-bedroom/process/02-interior-refresh-blue-in-progress.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/ryan-kitchen/after/01-ryans-kitchen-after-done-preview.webp": {
    width: 1600,
    height: 2133,
  },
  "/images/projects/ryan-kitchen/after/01-ryans-kitchen-after-done.jpg": {
    width: 3024,
    height: 4032,
  },
  "/images/projects/ryan-kitchen/before/01-ryans-kitchen-before.jpg": {
    width: 3024,
    height: 4032,
  },
};

const fallbackDimensions = { width: 1200, height: 900 };

export function getProjectImageDimensions(src: string) {
  return projectImageDimensions[src] ?? fallbackDimensions;
}
